### PR TITLE
Fix docblock

### PR DESCRIPTION
**Pull request by ossinkine**
PHPStan alerts second parameter should always be null

### CODE REVIEW

**Comment by acelaya** [comment]
PHPstan is now failing. I think you should just remove the `null` in the doc (it was probably added by my IDE), instead of adding the `string` type hints.

Future versions of this package will suport PHP 7.X only, fixing this problem.

**Comment by ossinkine** [comment]
@acelaya PHPStan failure is not related to this PR

**Comment by acelaya** [comment]
Right. Then I'll try to fix it so that you can rebase

**Comment by acelaya** [comment]
The problem was caused because I was installing phpstan without version. It fails with the latest one.

I'm fixing it and pushing it to master.

**Comment by acelaya** [comment]
It's up now. You can rebase.

**Comment by acelaya** [comment]
Just realized I have had to fix this. Thanks anyway :-)

**Pull request closed without merging**
