### PR TITLE
Fix create a new custom type

### PR DESCRIPTION
**Pull request by toofff**

### CODE REVIEW

**Comment by acelaya** [comment]
I have just broken the master branch build. Just right now.

Give me 2 minutes to fix it.

**Comment by toofff** [comment]
@acelaya I just saw that, I looked to make a new pull request.

Good luck.

**Comment by acelaya** [comment]
Done. You can rebase and push again.

**Comment by toofff** [comment]
@acelaya it's good for me

**Comment by acelaya** [comment]
Thanks for fixing this :-)

I'll release it as a hotfix once all builds pass.

**Comment by acelaya** [comment]
Already released as 2.0.2

**Pull request merged**
